# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "legal-document-summarizer.fullname" . }}
spec:
  selector:
    app: {{ include "legal-document-summarizer.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
